### ISSUE TITLE
React 18 support?

### ISSUE THREAD

**Issue by pastelmind** [stephenc222/react-panel-system#2]
Hi. I'm interested in your library. However, it's peer dependency is set to `react@^17.0.2`, which prevents me from using it (my project uses React 18). Would it be possible to support React 18?

**Comment by stephenc222** [comment]
@pastelmind Thanks for checking out my package! I've now published  version [v1.0.4](https://www.npmjs.com/package/react-panel-system) to support React 18. Let me know if you have any issues with React 18 support.
